name: padelly
description: A new Flutter application
publish_to: "none" # Remove this line if you wish to publish to pub.de
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9
  flutter_map: ^2.2.0
  flutter_map_location_marker: ^4.1.4
  flutter_map_marker_cluster: ^0.5.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    mage_path: "assets/images/appIcon.png"
    icon_size: 48 # min:48, max:256, default: 48

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#00a08b"
  image: assets/images/logoSmall.png
  android+gravity: fill

flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  uses-material-design: true

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
